### ISSUE TITLE
[ Interviews ] URL 

### ISSUE THREAD

**Issue by ghuerte** [IbinexPH/encryptoearth#22]
. When clicked in the navigation bar, the site redirects to `http://www.encryptoearth.com/category/news/interviews/` has no content while `http://www.encryptoearth.com/category/interviews/` has contents

**Comment by ghuerte** [comment]
![image](https://user-images.githubusercontent.com/37136794/39463276-b0c770d2-4d49-11e8-8511-1037243a8a43.png)

**Comment by ghuerte** [comment]
It seems the logged in user can access the articles in the page

**Comment by ricky-cabugawan** [comment]
wpfc plugin causes this issue. plugin temporarily deactivated.
