### ISSUE TITLE
[ Contact US ] Cryptoearth  must be com not cc

### ISSUE THREAD

**Issue by ghuerte** [IbinexPH/encryptoearth#23]
![image](https://user-images.githubusercontent.com/37136794/39462809-a291a490-4d46-11e8-9a09-41302f836efe.png)

**Comment by ghuerte** [comment]
![image](https://user-images.githubusercontent.com/37136794/39462814-b50f09b4-4d46-11e8-9d0b-bcd7ab78756f.png)

**Comment by chesterAlmonte** [comment]
done
